PC_PWD="123456"
PROJECT_ID='c385ev'
CHANNEL =0
ignore_init_send =False
PowerSig = {'BcmPwrStsFb':'2','IbBrkPedlStsGb':'101'}
main_can = "CAN1"
local_machine_Sender=['CDC']
SubNet_Frame ={'ICAN':14,'RCAN':0,'ISCAN':0,"HCAN":14} 
VFrameFormat={'StandardCAN':0,'ExtendedCAN':1,'StandardCAN_FD':14,'ExtendedCAN_FD':15}
Sig_Matrix='5_Matrix'
Message_Matrix='4_OverView'
MSB=False
SubNet_Channel={'ICAN':"CAN1",'RCAN':'CAN0','ISCAN':'CAN0','HCAN':'CAN2',"Other":'CAN1'}
Jira_Project = "BGS"
