#!/bin/bash

# echo "docker exec -i kiara_build_18 bash"
# docker exec -i kiara_build_18 bash  <<EOF
# cd  ~/Works/Repos/tool_parser 
# sudo make
# exit 0
# EOF

# parser=~/Works/Repos/changan_c835_release
parser=~/Works/Repos/changan_c835
toolDir=~/Works/Repos/canmatrix_tool/tool_parser

cd  $toolDir 
echo '123456' | sudo -S make

echo "删除原来的文件"
for f in `ls $parser/src/ic_service/parser/generated/`;
do
    if [ $f != "parser_net" ] ;then
        rm -rf $f
        echo $f
    fi
done

rm -rf common_codes

echo "开始拷贝"
cp -r $toolDir/output/* $parser/src/ic_service/parser/generated

cd $parser/src/ic_service/parser
git status

echo "拷贝完成"
