#!/bin/bash

echo "docker exec -i kiara_build_18 bash"
docker exec -i kiara_build_18 bash  <<EOF
cd  ~/Works/Repos/tool_parser 
sudo make
exit 0
EOF

echo "删除原来的文件"
rm -rf ~/Works/Repos/changan_c835/src/ic_service/parser/generated/

echo "开始拷贝"
cp -r ~/Works/Repos/tool_parser/output ~/Works/Repos/changan_c835/src/ic_service/parser/generated

cd ~/Works/Repos/changan_c835/src/ic_service/parser/generated
git status

echo "拷贝完成"
