#!/bin/bash

# echo "docker exec -i kiara_build_18 bash"
# docker exec -i kiara_build_18 bash  <<EOF
# cd  ~/Works/Repos/tool_parser 
# sudo make
# exit 0
# EOF

parser=$(cd `dirname ./`;pwd)

if [ $# -ge 1 ]; then
    parser=$parser/$1
fi
toolDir=$parser/canmatrix/

if [ ! -d "$toolDir" ]; then
    toolDir=$parser/src/ic_service/tools/canmatrix
fi

cd  $toolDir 
make

# echo "删除原来的文件"
# for f in `ls $parser/src/ic_service/parser/generated/`;
# do
#     if [ $f != "parser_net" ] ;then
#         rm -rf $f
#         echo $f
#     fi
# done

# rm -rf common_codes

# echo "开始拷贝"
# cp -r $toolDir/output/* $parser/src/ic_service/parser/generated/

cd $parser/src/ic_service
git status

# echo "拷贝完成"
