# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\chengxiong.zhu\Desktop\Achievement\pythonscript\toolWidget\dlg\projectDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(699, 161)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.projectPathLE_2 = QtWidgets.QLabel(Dialog)
        self.projectPathLE_2.setMinimumSize(QtCore.QSize(110, 0))
        self.projectPathLE_2.setObjectName("projectPathLE_2")
        self.horizontalLayout_5.addWidget(self.projectPathLE_2)
        self.prjectNameLE = QtWidgets.QLineEdit(Dialog)
        self.prjectNameLE.setText("")
        self.prjectNameLE.setObjectName("prjectNameLE")
        self.horizontalLayout_5.addWidget(self.prjectNameLE)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.projectPath = QtWidgets.QLabel(Dialog)
        self.projectPath.setMinimumSize(QtCore.QSize(110, 0))
        self.projectPath.setObjectName("projectPath")
        self.horizontalLayout_2.addWidget(self.projectPath)
        self.projectPathLE = QtWidgets.QLineEdit(Dialog)
        self.projectPathLE.setText("")
        self.projectPathLE.setObjectName("projectPathLE")
        self.horizontalLayout_2.addWidget(self.projectPathLE)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(110, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.tsPathLE = QtWidgets.QLineEdit(Dialog)
        self.tsPathLE.setText("")
        self.tsPathLE.setObjectName("tsPathLE")
        self.horizontalLayout_3.addWidget(self.tsPathLE)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(110, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.wanTextLE = QtWidgets.QLineEdit(Dialog)
        self.wanTextLE.setText("")
        self.wanTextLE.setObjectName("wanTextLE")
        self.horizontalLayout_4.addWidget(self.wanTextLE)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.addbtn = QtWidgets.QPushButton(Dialog)
        self.addbtn.setObjectName("addbtn")
        self.horizontalLayout.addWidget(self.addbtn)
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.projectPathLE_2.setText(_translate("Dialog", "项目名称:"))
        self.projectPath.setText(_translate("Dialog", "项目路径:"))
        self.label_2.setText(_translate("Dialog", "ts路径:"))
        self.label_3.setText(_translate("Dialog", "弹窗配置文件路径:"))
        self.addbtn.setText(_translate("Dialog", "添加"))
        self.cancelBtn.setText(_translate("Dialog", "关闭"))
