#ifndef DRAWTOOLPUBLIC_GLOBAL_H
#define DRAWTOOLPUBLIC_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DRAWTOOLPUBLIC_LIBRARY)
#  define DRAWTOOLPUBLIC_EXPORT Q_DECL_EXPORT
#else
#  define DRAWTOOLPUBLIC_EXPORT Q_DECL_IMPORT
#endif

#endif // DRAWTOOLPUBLIC_GLOBAL_H
