# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\chengxiong.zhu\Desktop\Achievement\pythonscript\toolWidget\customWidget\lableLineEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_lableLineEdit(object):
    def setupUi(self, lableLineEdit):
        lableLineEdit.setObjectName("lableLineEdit")
        lableLineEdit.resize(817, 38)
        self.horizontalLayout = QtWidgets.QHBoxLayout(lableLineEdit)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLineEdit(lableLineEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(lableLineEdit)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)

        self.retranslateUi(lableLineEdit)
        QtCore.QMetaObject.connectSlotsByName(lableLineEdit)

    def retranslateUi(self, lableLineEdit):
        _translate = QtCore.QCoreApplication.translate
        lableLineEdit.setWindowTitle(_translate("lableLineEdit", "Form"))
